version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres_hatsumei
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_hatsumei:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    container_name: backend_hatsumei
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      FLASK_APP: run.py
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/backend
    command: ["/backend/entrypoint.sh"]

volumes:
  postgres_hatsumei:
    name: postgres_hatsumei